name: CI/CD & Nodejs App 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code 
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: docker build -t cicd-docker-nodejsapp .

  login:
    runs-on: ubuntu-latest
    needs: build  # Dieser Job wartet, bis der "build" Job abgeschlossen ist.

    steps:
    - name: Check Docker Username Secret
      run: echo ${{ secrets.DOCKER_USERNAME }}
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  push:
    runs-on: ubuntu-latest
    needs: [build, login]  # Dieser Job wartet, bis die "build" und "login" Jobs abgeschlossen sind.

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Tag and Push Image to Docker Hub
      run: |
        docker images  # Listet alle verfügbaren Images auf, um sicherzustellen, dass das Image existiert
        docker tag cicd-docker-nodejsapp ${{ secrets.DOCKER_USERNAME }}/cicd-docker-nodejsapp:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/cicd-docker-nodejsapp:latest

        
